const express = require("express");
const router = express.Router();
const nodemailer = require("nodemailer");

function createTransporter() {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST || "smtp.gmail.com",
    port: parseInt(process.env.EMAIL_PORT || "587"),
    secure: false,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
}

function buildReportHTML(reportData) {
  const { domain, score, findings, plainEnglishSummary, fixGuide, emailSecurity } = reportData;
  const scoreColor = score?.color || "#eab308";

  const fixSteps = fixGuide
    ?.map(
      (s, i) => `
    <div style="margin-bottom:16px; padding:12px; background:#f8fafc; border-left:4px solid #0ea5e9; border-radius:4px;">
      <strong style="color:#0f172a;">Step ${i + 1}: ${s.title}</strong>
      <p style="margin:4px 0 0; color:#475569;">${s.description}</p>
      <span style="font-size:12px; color:#64748b;">Effort: ${s.effort}</span>
    </div>`
    )
    .join("") || "<p>No fix steps required.</p>";

  return `
    <div style="font-family: 'Segoe UI', sans-serif; max-width:600px; margin:0 auto; color:#0f172a;">
      <div style="background:#0f172a; padding:24px; border-radius:8px 8px 0 0;">
        <h1 style="color:#fff; margin:0; font-size:24px;">🛡️ CyberShield Security Report</h1>
        <p style="color:#94a3b8; margin:4px 0 0;">${domain} — ${new Date().toLocaleDateString()}</p>
      </div>
      <div style="background:#fff; padding:24px; border:1px solid #e2e8f0;">
        <div style="text-align:center; margin-bottom:24px;">
          <div style="display:inline-block; width:80px; height:80px; border-radius:50%; background:${scoreColor}; line-height:80px; font-size:28px; font-weight:bold; color:#fff;">
            ${score?.value || "N/A"}
          </div>
          <p style="font-size:18px; font-weight:600; margin:8px 0 0;">${score?.band || "Unknown"} Security</p>
        </div>
        <h2 style="color:#0f172a; font-size:16px;">Summary</h2>
        <p style="color:#475569;">${plainEnglishSummary || "Scan complete."}</p>
        <h2 style="color:#0f172a; font-size:16px; margin-top:24px;">Your Fix Plan</h2>
        ${fixSteps}
      </div>
      <div style="background:#f1f5f9; padding:16px; border-radius:0 0 8px 8px; text-align:center;">
        <p style="color:#64748b; font-size:12px; margin:0;">Generated by CyberShield — Protecting small businesses</p>
      </div>
    </div>
  `;
}

// POST /api/report/email
router.post("/email", async (req, res) => {
  const { to, reportData } = req.body;
  if (!to || !reportData) return res.status(400).json({ error: "to and reportData are required" });

  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    return res.json({
      success: true,
      note: "Email not configured. Set EMAIL_USER and EMAIL_PASS in .env to send real emails.",
      reportData,
    });
  }

  try {
    const transporter = createTransporter();
    await transporter.sendMail({
      from: process.env.EMAIL_FROM || "CyberShield <security@cybershield.app>",
      to,
      subject: `Security Report for ${reportData.domain} — Score: ${reportData.score?.value}/100`,
      html: buildReportHTML(reportData),
    });
    res.json({ success: true, message: `Report sent to ${to}` });
  } catch (err) {
    res.status(500).json({ error: `Failed to send email: ${err.message}` });
  }
});

// POST /api/report/generate
router.post("/generate", (req, res) => {
  const { reportData } = req.body;
  if (!reportData) return res.status(400).json({ error: "reportData required" });

  res.json({
    html: buildReportHTML(reportData),
    generatedAt: new Date().toISOString(),
  });
});

module.exports = router;
