import nodemailer from 'nodemailer';

function hasSmtpConfig() {
  return Boolean(process.env.SMTP_HOST && process.env.SMTP_PORT && process.env.SMTP_USER && process.env.SMTP_PASS);
}

function createTransport() {
  if (!hasSmtpConfig()) {
    return null;
  }

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT),
    secure: String(process.env.SMTP_SECURE || 'false') === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

export async function sendReportEmail(report, recipientEmail) {
  const transport = createTransport();
  const subject = `RAVEN Security Report - ${report.business_name || report.domain}`;
  const text = [
    `Security score: ${report.score}/100`,
    `Band: ${report.band}`,
    `Top summary: ${report.summary_message || 'No summary available.'}`,
    '',
    'This report was generated by RAVEN.',
  ].join('\n');

  if (!transport) {
    console.log(`Email delivery is not configured. Report for ${recipientEmail} was prepared locally.`);
    return {
      message: `Email delivery is not configured. Prepared the report for ${recipientEmail}.`,
      simulated: true,
    };
  }

  await transport.sendMail({
    from: process.env.EMAIL_FROM || process.env.SMTP_USER,
    to: recipientEmail,
    subject,
    text,
  });

  return {
    message: `Report sent to ${recipientEmail}.`,
    simulated: false,
  };
}
